### ISSUE TITLE
Checkbox values are not being sent to the server

### ISSUE THREAD

**Issue by andyfusniak** [capturoo/capturoo-js-client-sdk#2]
To repeat, click Fish, Pie and Fruit options in the checkbox. Only the last item value is sent.

We should expect to capture an Array of item values or empty array if none are checked.

```html
<html>

<head>
  <script src="https://code.capturoo.com/capturoo-sdk-0.3.0.js"></script>
</head>

<body>

<form id="christmasform" method="post" accept-charset="utf-8">

<div>
  <input type="text" name="firstname">
</div>

<div>
  <label for="fish">Fish</label>
  <input id="fish" type="checkbox" name="food" value="fish">
</div>

<div>
  <label for="pie">Pie</label>
  <input id="pie" type="checkbox" name="food" value="pie">
</div>

<div>
  <label for="fruit">Fruit</label>
  <input id="fruit" type="checkbox" name="food" value="fruit">
</div>


<button>SEND</button>


</form>

<script>
var client = new CapturooClient({
  publicApiKey: 'CbKZ9fKwmKP6HvnV'
});

client.setForm('christmasform');
</script>
</body>

</html>
```

```yaml
- 
  leadData: 
    food:      fruit
    firstname: Andy
  systemData: 
    port:      8887
    host:      127.0.0.1:8887
    referrer:  
    userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
    ip:        ::ffff:0.0.0.0
    protocol:  http:
  trackingData: 
    utmTerm:     test-term
    utmSource:   test-source
    utmCampaign: test-campaign
    utmMedium:   test-medium
    utmContent:  test-content
  leadId:       BRu004ANWtyoK7JMVFxp
```
